version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absensi-app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: absensi-nginx
    ports:
      - "8000:80"       # web Laravel
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  reverb:
    image: php:8.3-cli
    container_name: absensi-reverb
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8002
    ports:
      - "8002:8002"
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: absensi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: absensi
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
